---
version: "2"
services:
  ddclient:
    container_name: ddclient
    environment:
      - PGID=1000
      - TZ=America/New_York
    image: linuxserver/ddclient:latest
    restart: unless-stopped
    volumes:
      - /mnt/docker_vols/ddclient/config:/config
  homebridge:
    container_name: homebridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - HOMEBRIDGE_CONFIG_UI_PORT=8000
      - HOMEBRIDGE_CONFIG_UI=1
    image: oznu/homebridge:latest
    networks:
      lan:
        ipv4_address: ${HOMEBRIDGE_IP}
    ports:
      - 8080:8080/tcp
    restart: unless-stopped
    volumes:
      - /mnt/docker_vols/homebridge:/homebridge
  letsencrypt:
    cap_add:
      - NET_ADMIN
    container_name: letsencrypt
    environment:
      - PUID=1000
      - PGID=1000
      - 'TZ=America/New_York'
      - URL=${HOME_HOSTNAME}
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    image: linuxserver/letsencrypt:latest
    networks:
      - mybridge
    ports:
      - 443:443/tcp
      - 80:80/tcp
    restart: unless-stopped
    volumes:
      - /mnt/docker_vols/letsencrypt/config:/config
  plex:
    container_name: plex
    environment:
      - VERSION=docker
    image: linuxserver/plex:latest
    networks:
      lan: 
        ipv4_address: ${PLEX_IP}
    ports:
      - 32400:32400/tcp
    restart: unless-stopped
    volumes:
      - /mnt/docker_vols/plex/config:/config
      - /mnt/shared/tvshows:/tvshows
      - /mnt/shared/movies:/movies
      - /mnt/shared/downloads:/downloads
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    networks:
      - mybridge
    ports:
      - 8000:8000/tcp
      - 9000:9000/tcp
    restart: unless-stopped
    volumes:
      - /mnt/docker_vols/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock     
  timemachine:
    command:
      - /entrypoint.sh
    container_name: timemachine
    environment:
      - PUID=1000
      - PGID=1000
      - AFP_LOGIN=${TIMEMACHINE_USER}
      - 'AFP_PASSWORD=${TIMEMACHINE_PASS}'
      - AFP_NAME=timemachine
    image: odarriba/timemachine:latest
    networks:
      - mybridge
    ports:
      - 548:548/tcp
      - 636:636/tcp
    restart: unless-stopped
    ulimits:
      nofile:
        hard: 65536
        soft: 65536
    volumes:
      - /mnt/timemachine:/timemachine
  radarr:
    container_name: radarr
    hostname: radarr
    image: linuxserver/radarr:latest
    networks:
      - mybridge
    ports:
      - 7878:7878/tcp
    restart: unless-stopped
    volumes:
      - /mnt/docker_vols/radarr/config:/config
      - /mnt/shared:/shared
  sonarr:
    container_name: sonarr
    hostname: sonarr
    image: linuxserver/sonarr:latest
    networks:
      - mybridge
    ports:
      - 8989:8989/tcp
    restart: unless-stopped
    volumes:
      - /mnt/docker_vols/sonarr/config:/config
      - /mnt/shared:/shared
      - /dev/rtc:/dev/rtc
  jackett:
    container_name: jackett
    hostname: jackett
    image: linuxserver/jackett:latest
    networks:
      - mybridge
    ports:
      - 9117:9117/tcp
    restart: unless-stopped
    volumes:
      - /mnt/docker_vols/jackett/config:/config
  transmission:
    cap_add:
      - NET_ADMIN
    container_name: transmission
    environment:
      - 'OPENVPN_USERNAME=${TORGUARD_USER}'
      - OPENVPN_PASSWORD=${TORGUARD_PASS}
      - 'LOCAL_NETWORK=${LOCAL_NET}/24'
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=CUSTOM
      - TRANSMISSION_DOWNLOAD_DIR=/download
      - TRANSMISSION_IDLE_SEEDING_LIMIT=1
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=1
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_SEED_QUEUE_SIZE=3
    hostname: transmission
    image: haugene/transmission-openvpn:latest
    networks:
      - mybridge
    ports:
      - 9091:9091/tcp
    restart: unless-stopped
    volumes:
      - /mnt/shared/downloads:/downloads
      - /mnt/shared/transmission/data:/data
      - /mnt/docker_vols/transmission/config:/config
      - /mnt/docker_vols/transmission/config.ovpn:/etc/openvpn/custom/default.ovpn
      - /mnt/docker_vols/transmission/data:/data/transmission-home/torrents/
  zoneminder:
    container_name: zoneminder
    image: dlandon/zoneminder:latest
    restart: unless-stopped
    ports:
      - 8443:443/tcp
      - 9001:9000/tcp
    networks:
      - mybridge
    privileged: true
    environment:
      - TZ=America/New_York
      - SHMEM=50%
      - PUID=1000
      - PGID=1000
      - INSTALL_HOOK=0
      - INSTALL_FACE=0
      - INSTALL_TINY_YOLO=0
      - INSTALL_YOLO=0
      - MULTI_PORT_START=0
      - MULTI_PORT_END=0
    volumes:
      - /mnt/docker_vols/zoneminder/config:/config:rw
      - /mnt/zoneminder/cache:/var/cache/zoneminder:rw
networks:
  mybridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
  lan:
    driver: macvlan
    driver_opts:
      parent: ${LAN_INTERFACE}
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
